name: Node.js CI

on: push

jobs:
  build-front:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Open webapp directory
        run: cd webapp

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run tests
        run: yarn build

  build-back:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 20 ]
        distribution: [ 'corretto' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: distribution

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

      - name: Build
        run: mvn build